spring:
  application:
    name: user
server:
  port: 8002
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

info:
  app.name: user
  build.artifactId: $project.artifactId$
  build.version: $project.version$
feign:
  hystrix:
    enabled: true